// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOctAdUEbv9yY8qQRv6FMWyfI4EJyq8vs',
    appId: '1:180613275932:web:5f0e38f33ad1fa67155ad9',
    messagingSenderId: '180613275932',
    projectId: 'to-do-list-d57dc',
    authDomain: 'to-do-list-d57dc.firebaseapp.com',
    storageBucket: 'to-do-list-d57dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0Akv5jCIWBrJnfZGS_TUABKDvAQoJbg',
    appId: '1:180613275932:android:9f0c28000aa3ce1e155ad9',
    messagingSenderId: '180613275932',
    projectId: 'to-do-list-d57dc',
    storageBucket: 'to-do-list-d57dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz10ck1sS6cHwzuedV2PWYxQMG7L9L36U',
    appId: '1:180613275932:ios:4f89149b44e0ed67155ad9',
    messagingSenderId: '180613275932',
    projectId: 'to-do-list-d57dc',
    storageBucket: 'to-do-list-d57dc.firebasestorage.app',
    iosBundleId: 'com.example.todolistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz10ck1sS6cHwzuedV2PWYxQMG7L9L36U',
    appId: '1:180613275932:ios:4f89149b44e0ed67155ad9',
    messagingSenderId: '180613275932',
    projectId: 'to-do-list-d57dc',
    storageBucket: 'to-do-list-d57dc.firebasestorage.app',
    iosBundleId: 'com.example.todolistapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOctAdUEbv9yY8qQRv6FMWyfI4EJyq8vs',
    appId: '1:180613275932:web:60717079e2aea3dc155ad9',
    messagingSenderId: '180613275932',
    projectId: 'to-do-list-d57dc',
    authDomain: 'to-do-list-d57dc.firebaseapp.com',
    storageBucket: 'to-do-list-d57dc.firebasestorage.app',
  );
}
